export default {
  "login": "parth-27",
  "id": 54990846,
  "node_id": "MDQ6VXNlcjU0OTkwODQ2",
  "avatar_url": "https://avatars2.githubusercontent.com/u/54990846?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/parth-27",
  "html_url": "https://github.com/parth-27",
  "followers_url": "https://api.github.com/users/parth-27/followers",
  "following_url": "https://api.github.com/users/parth-27/following{/other_user}",
  "gists_url": "https://api.github.com/users/parth-27/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/parth-27/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/parth-27/subscriptions",
  "organizations_url": "https://api.github.com/users/parth-27/orgs",
  "repos_url": "https://api.github.com/users/parth-27/repos",
  "events_url": "https://api.github.com/users/parth-27/events{/privacy}",
  "received_events_url": "https://api.github.com/users/parth-27/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Parth Patel",
  "company": "SEAS, Ahmedabad University",
  "blog": "",
  "location": "Navsari, Gujarat",
  "email": null,
  "hireable": null,
  "bio": "Impossible is just an opinion.",
  "twitter_username": "parthpatel_27",
  "public_repos": 17,
  "public_gists": 0,
  "followers": 43,
  "following": 83,
  "created_at": "2019-09-06T14:14:16Z",
  "updated_at": "2021-01-05T06:05:48Z"
};